version: "3.8"
services:
    django:
        build: ./web
        volumes:
            - static:/app/static
        environment:
            - SECRET_KEY=MakeThisALongRandomStringForProduction
            - DEBUG=False
            - ALLOWED_HOSTS=your.website.com,subdomain.website.com
        restart: always
    nginx:
        image: nginx:1.19
        depends_on:
            - django
        ports:
            - 8081:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static:/serve/static
        restart: always

volumes:
    static:
