version: "3.8"
services:
    django:
        build: ./web
        volumes:
            - static:/app/static
        environment:
            - SECRET_KEY=MakeThisALongRandomStringForProduction
            - DEBUG=False
            - ALLOWED_HOSTS=192.168.1.111
    nginx:
        image: nginx:1.19
        depends_on:
            - django
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static:/serve/static

volumes:
    static:
